name: aspnet-7.0-jammy-amd64

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ./aspnet/7.0-jammy/Dockerfile
          push: true
          tags: xlievo/aspnet:7.0-jammy-amd64
