name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ./aspnet/alpine.3.17-sdk/Dockerfile
          push: true
          tags: xlievo/dotnet-sdk-alpine:7.0.103-3.17-v1
