name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file ./aspnet/alpine.3.17-sdk/Dockerfile --tag dotnet-sdk-alpine:7.0.103-3.17-v1
