name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file aspnet/6.0-focal/Dockerfile --tag aspnet:6.0-focal
    - name: Dockerize
      if: success()
      uses: manusa/actions-publish-docker@v1.1.2
      with:
        name: organization/image_name
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
