name: dotnet-sdk-7.0-alpine3.18-amd64

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    -
        name: Build and push sdk
        uses: docker/build-push-action@v4
        with:
          file: ./dotnet/sdk-7.0-alpine3.18-amd64
          push: true
          tags: xlievo/dotnet:sdk-7.0-alpine3.18-amd64
    -
        name: Build and push alpine
        uses: docker/build-push-action@v4
        with:
          file: ./dotnet/alpine3.18-amd64
          push: true
          tags: xlievo/dotnet:alpine3.18-amd64
